[world]
file = "cornell.obj"
light= { center = [0.0, 0.95, 0.0], a = [0.9, 0.0, 0.0], b = [0.0, 0.0, 0.9], I = [1, 1, 0.7]}

[camera]
size = [400,300]
orig = [0,0,-3]
look_at = [0,0.1,0]
rays_per_pixel = 15
steps = 3
threads = 16
super_sampling_factor = 3
horizontal_angle = 65